SET search_path = vetosansfrontieresDB;

DROP SCHEMA IF EXISTS VETOSANSFRONTIERESDB CASCADE;
CREATE SCHEMA VETOSANSFRONTIERESDB;

CREATE DOMAIN VETOSANSFRONTIERESDB.sexType AS CHAR
	CHECK (VALUE IN ('M', 'F'));

CREATE TABLE IF NOT EXISTS VETOSANSFRONTIERESDB.Personnel(
personnelNo VARCHAR(10) NOT NULL,
cliniqueNo  VARCHAR(10)	NOT NULL,
prenom VARCHAR(50)	NOT NULL,
nomDeFamille VARCHAR(50)	NOT NULL,
adresse VARCHAR(100)	NOT NULL,
numTelephone VARCHAR(70)	NULL,
dateDeNaissance DATE	NOT NULL,
nas	VARCHAR(10)	UNIQUE NOT NULL,
sexe sexType DEFAULT 'M',
fonction VARCHAR(50) NOT NULL,
salaire  INTEGER NOT NULL,

PRIMARY KEY (personnelNo));


CREATE TABLE IF NOT EXISTS VETOSANSFRONTIERESDB.Clinique(
cliniqueNo VARCHAR(10) NOT NULL,
cliniqueNom VARCHAR(50) NOT NULL,
gestionNo  VARCHAR(10)	NOT NULL,
rue VARCHAR(50)	NOT NULL,
ville VARCHAR(50)	NOT NULL,
province VARCHAR(50)	NOT NULL,
codePostal VARCHAR(10)	NOT NULL,
numTelephone VARCHAR(10)	NULL,
numTelecopieur VARCHAR(10)	NULL,

PRIMARY KEY (cliniqueNo),
FOREIGN KEY(gestionNo) REFERENCES VETOSANSFRONTIERESDB.Personnel(personnelNo) ON DELETE RESTRICT ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS VETOSANSFRONTIERESDB.Proprietaire(
cliniqueNo VARCHAR(10) NOT NULL,
propNo  VARCHAR(10)	NOT NULL,
nom VARCHAR(50)	NOT NULL,
numTelephone VARCHAR(10) NULL,
adresse VARCHAR(70)	NOT NULL,

PRIMARY KEY (cliniqueNo,propNo),
FOREIGN KEY(cliniqueNo) REFERENCES VETOSANSFRONTIERESDB.Clinique(cliniqueNo) ON DELETE RESTRICT ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS VETOSANSFRONTIERESDB.Traitement(
traitementNo VARCHAR(10) NOT NULL,
description  VARCHAR(70)	NOT NULL,
cout DECIMAL NOT NULL,

PRIMARY KEY (traitementNo));


CREATE TABLE IF NOT EXISTS VETOSANSFRONTIERESDB.TraitementClinique(
cliniqueNo VARCHAR(10) NOT NULL,
traitementNo VARCHAR(10) NOT NULL,


PRIMARY KEY (cliniqueNo,traitementNo),
FOREIGN KEY(cliniqueNo) REFERENCES VETOSANSFRONTIERESDB.Clinique(cliniqueNo) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(traitementNo) REFERENCES VETOSANSFRONTIERESDB.Traitement(traitementNo) ON DELETE RESTRICT ON UPDATE CASCADE);




CREATE TABLE IF NOT EXISTS VETOSANSFRONTIERESDB.Animal(
cliniqueNo VARCHAR(10) NOT NULL,
animalNo  VARCHAR(10)	NOT NULL,
propNo  VARCHAR(10)	NOT NULL,
nom VARCHAR(20)	NOT NULL,
Atype VARCHAR(20)	NOT NULL,
description VARCHAR(50)	NOT NULL,
dateDeNaissance DATE NOT NULL,
dateInscription DATE NOT NULL,
etat  VARCHAR(10)	NOT NULL,

PRIMARY KEY (cliniqueNo,animalNo),
FOREIGN KEY(cliniqueNo,propNo) REFERENCES VETOSANSFRONTIERESDB.Proprietaire(cliniqueNo,propNo) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(cliniqueNo) REFERENCES VETOSANSFRONTIERESDB.Clinique(cliniqueNo) ON DELETE RESTRICT ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS VETOSANSFRONTIERESDB.Examen(
examenNo VARCHAR(10) NOT NULL,
cliniqueNo VARCHAR(10) NOT NULL,
animalNo  VARCHAR(10)	NOT NULL,
personnelNo  VARCHAR(10)	NOT NULL,
dateE DATE NOT NULL,
heure TIME NOT NULL,
description VARCHAR(50)	NOT NULL,

PRIMARY KEY (examenNo),
FOREIGN KEY(personnelNo) REFERENCES VETOSANSFRONTIERESDB.Personnel(personnelNo) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(cliniqueNo,animalNo) REFERENCES VETOSANSFRONTIERESDB.Animal(cliniqueNo,animalNo) ON DELETE RESTRICT ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS VETOSANSFRONTIERESDB.TraitementExamen(
examenNo VARCHAR(10) NOT NULL,
traitementNo VARCHAR(10) NOT NULL,
quantite INTEGER NOT NULL,
dateCommence DATE NOT NULL,
dateFini DATE NULL,

PRIMARY KEY (examenNo,traitementNo),
FOREIGN KEY(examenNo) REFERENCES VETOSANSFRONTIERESDB.Examen(examenNo) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(traitementNo) REFERENCES VETOSANSFRONTIERESDB.Traitement(traitementNo) ON DELETE RESTRICT ON UPDATE CASCADE);


ALTER TABLE VETOSANSFRONTIERESDB.Clinique
   ADD CONSTRAINT fk_clinique
   FOREIGN KEY (cliniqueNo)
   REFERENCES VETOSANSFRONTIERESDB.Clinique(cliniqueNo) ON DELETE RESTRICT ON UPDATE CASCADE;
